# Generated by Django 3.1.1 on 2021-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Currency',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
